name: clock_app
description: "Its a clock app, what else do you want to know?"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0  # Add this line to include the intl package
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets here for your app icon and other images
  assets:
    - assets/icons/clock_icon.png  # Place your icon here

  # If you need custom fonts, uncomment and add them below
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/clock_icon.png"
